[project]
name = "mcp-cmpay"
version = "0.1.0"
description = "mcp cmpay server"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cryptography==44.0.3",
    "httpx>=0.28.1",
    "mcp[cli]==1.8.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/mcp-cmpay"]

[project.optional-dependencies]
test = ["pytest", "pytest-cov"]

[project.scripts]
duckduckgo-mcp-server = "mcp-cmpay.server:main"