[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "data_buyer_toolkit"
version = "0.1.3"  # bump to 0.1.1 for republishing
description = "Toolkit for identifying third-party data buyers in U.S. federal job postings from USAJobs."
readme = "data_buyer_toolkit/README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
  {name = "Rory G. Quinlan"},
]
dependencies = [
  "pandas",
  "numpy",
  "scikit-learn",
  "nltk",
  "requests",
  "rapidfuzz",
  "joblib",
]

[project.urls]
"Homepage" = "https://github.com/RoryQo/Public-Sector-Data-Demand_Research-Framework-For-Market-Analysis-And-Classification"

[tool.setuptools.packages.find]
where = ["."]
include = ["data_buyer_toolkit", "data_buyer_toolkit.*"]

[tool.setuptools.package-data]
"data_buyer_toolkit" = ["*.joblib"]
