[package]
name = "qubed"
version = "0.2.0"
edition = "2021"
repository = "https://github.com/ecmwf/qubed"

[dependencies]
# rsfdb = {git = "https://github.com/ecmwf/rsfdb", branch = "develop"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
pyo3 = "0.23"

[package.metadata.maturin]
version-from-git = true

[lib]
name = "tree_traverser"
crate-type = ["cdylib"]
path = "./src/rust/lib.rs"

# [patch.'https://github.com/ecmwf/rsfdb']
# rsfdb = { path = "../rsfdb" }

# [patch.'https://github.com/ecmwf-projects/rsfindlibs']
# rsfindlibs = { path = "../rsfindlibs" }
