[project]
name = "turbodl"
version = "0.6.1"
description = "TurboDL is an extremely smart, fast, and efficient download manager designed to optimize your downloading experience."
license = "MIT"
readme = "README.md"
authors = [
    { name = "henrique-coder", email = "henriquemoreira10fk@gmail.com" }
]
maintainers = [
    { name = "henrique-coder", email = "henriquemoreira10fk@gmail.com" }
]
keywords = [
    "dl",
    "downloader",
    "manager",
    "python",
    "smart",
    "turbodl"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Internet",
    "Topic :: Software Development :: Libraries",
    "Typing :: Typed"
]
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "humanfriendly>=10.0",
    "psutil>=7.0.0",
    "rich>=14.0.0",
    "streamsnapper",
    "tenacity>=9.1.2",
]

[tool.uv.sources]
streamsnapper = { git = "https://github.com/henrique-coder/streamsnapper.git" }

[project.optional-dependencies]
cli = [
  "click==8.1.8",
  "typer>=0.15.3",
]

[dependency-groups]
dev = [
    "fastapi>=0.115.12",
]
lint = [
    "ruff>=0.11.9",
]
test = [
    "pytest>=8.3.5",
    "pytest-randomly>=3.16.0",
]

[project.urls]
homepage = "https://github.com/henrique-coder/turbodl"
documentation = "https://github.com/henrique-coder/turbodl/blob/main/README.md"
repository = "https://github.com/henrique-coder/turbodl"
"Bug Tracker" = "https://github.com/henrique-coder/turbodl/issues"
"Changelog" = "https://github.com/henrique-coder/turbodl/releases/latest"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_functions = ["test_*"]

[project.scripts]
turbodl = "turbodl.cli.__main__:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
