[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "lazy-settings"
version = "0.1.0"
description = "settings manaager for pyhton"
readme = "README.md"
requires-python = ">=3.11"
maintainers = [
    {name = "amirreza",email = "amir.rsf1380@gmail.com"},
]
classifiers = [
    "Programming Language :: Python",
    "Environment :: Web Environment",
    "Development Status :: 4 - Beta" ,
    "Topic :: Utilities",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = []

[dependency-groups]
dev = [
    "anyio>=4.9.0",
    "django>=5.2",
    "django-stubs>=5.1.3",
    "mypy>=1.15.0",
    "pre-commit>=4.2.0",
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1",
    "pytest-env>=1.1.5",
    "pytest-mock>=3.14.0",
    "pytest-order>=1.3.0",
    "ruff>=0.11.5",
    "trio>=0.29.0",
]

[project.urls]
Homepage = "https://github.com/khiyavan/lazy-settings"
Issues = "https://github.com/khiyavan/lazy-settings/issues"

[project.optional-dependencies]
rtoml = [
    "rtoml>=0.12.0",
]
tomli = [
    "tomli>=2.2.1",
]

[tool.mypy]
exclude = ["tests/"]

[lazy-settings]
SETTINGS_MODULE = "tests.django_settings"
