[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "PAGEpy"
version = "1.0.6"
authors = [
  { name="Sean O'Toole", email="sean.otoole.bio@gmail.com" },
]
description = "Predictive Analysis of Gene Expression"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICENSE"]

dependencies = [
    "numpy==2.1.3",         
    "pandas>=1.3,<2.1",     
    "scikit-learn>=1.0,<1.5", 
    "tensorflow==2.19.0",   
    "scanpy>=1.9.1,<1.10",  
    "anndata>=0.8.0,<0.11", 
    "matplotlib>=3.4,<3.8", 
    "scipy==1.15.3",        
    "seaborn>=0.11.0,<0.13"
]
[project.urls]
Homepage = "https://github.com/sean-otoole/PAGEpy"
