[project]
name = "rs-server-common"
version = "0.0.0" # see: https://github.com/mtkennerly/poetry-dynamic-versioning

[tool.poetry]
name = "rs-server-common"
version = "0.2a13"
description = "Copernicus Sentinel rs-server, common services."
license = "Apache-2.0"
authors = ["ESA under contract with Airbus and CS <ops_coprs@airbus.com>"]
readme = "README.md"
homepage = "https://home.rs-python.eu/"
repository = "https://github.com/RS-PYTHON/rs-server"
documentation = "https://home.rs-python.eu/rs-documentation/rs-server/docs/doc/"
keywords = ["stac", "copernicus", "sentinel", "processing"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: FastAPI",
    "Framework :: OpenTelemetry",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: GIS",
    "Topic :: Scientific/Engineering :: Image Processing"
]

packages = [
    { include = "rs_server_common" },
    { include = "tests", format = "sdist" },
]

# Add configuration files to the .whl package
include = [
    { path = "config", format = ["wheel"] }
]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.12"
starlette = ">=0.46.2,<0.47"
boto3 = ">=1.35.40"
botocore = ">=1.35.99"
sqlalchemy = "^2.0.35"
eodag = "==v3.4.0"
# NOTE: to use a forked eodag version we would use:
# eodag = { git = "https://github.com/jgaucher-cs/eodag", branch = "my-branch-name" }
pydantic = ">=2.9.2,<2.12.0"
markdown = "^3.6"
python-dotenv = "^1.0.0"
filelock = "^3.16.1"
uvicorn = ">=0.31,<0.35"
httpx = "^0.27.2"
cachetools = ">=5.5.2" # idem as stac-fastapi-pgstac
asyncache = "^0.3.1"
opentelemetry-distro = "^0.53b1" # then run 'poetry run opentelemetry-bootstrap -a install'
opentelemetry-instrumentation-aws-lambda = "^0.53b1"
opentelemetry-test-utils = "^0.53b1"
opentelemetry-exporter-otlp = "^1.32.1"
python-logging-loki = "^0.3.1"
authlib = "^1.5.0"
python-keycloak = ">=5.3.1,<6.0"
itsdangerous = "^2.2.0"
pyjwt = {extras = ["crypto"], version = "^2.9.0"}
stac-fastapi-pgstac = "^5.0.2"
pydantic-settings = ">2.2.1,<3.0.0,!=2.9.0" # see https://github.com/PrefectHQ/prefect/issues/17852
pygeofilter = ">=0.3.1.post1"
stac-pydantic = "^3.1.4"
geojson-pydantic = "1.2.0" # to avoid regressions with 2.0.0
stac-fastapi-types = "5.2.0" # to avoid regressions with 5.2.1

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pygeofilter = { git = "https://github.com/RS-PYTHON/pygeofilter", branch = "rspy" }
pytest = "^8.3.3"
pytest-asyncio = "^0.24.0"
pytest-cov = "^6.0.0"
pytest-docker = "^3.1.0"
pytest-error-for-skips = "^2.0.2"
pytest-httpx = "^0.34.0"
pytest-mock = "^3.14.0"
responses = "^0.25.3"

[tool.black]
line-length = 120

[tool.pytest.ini_options]
markers = [
    "unit", # mark a test as unittest
    "integration", # mark a test as integration test
]
asyncio_default_fixture_loop_scope = "function"
asyncio_mode = "auto"

[tool.mypy]
warn_redundant_casts = true
# Force analyze of partially annotate function signatures
check_untyped_defs = true

[tool.poetry-dynamic-versioning] # needs: poetry self add "poetry-dynamic-versioning[plugin]"
enable = false
metadata = false

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"
