[project]
name = "pybifrost"
version = "1.0.17"
description = "A package for analysis of BIFROST simulation data and resolution functions"
authors = [
    { name = "Nicolai Amin", email = "nicolaiamin1@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
    "matplotlib==3.7.2",
    "numpy==1.24.3",
    "pandas==2.0.3",
    "scipy==1.11.4",
    "seaborn==0.13.2",
    "tqdm==4.65.0"
]

license = "MIT"
license-files = ["LICEN[CS]E*"]

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/pybifrost", "src/pybifrost.constants"]
include-package-data = true

[tool.setuptools.package-data]
"pybifrost/constants" = ["*.npy"]

[project.urls]
Homepage = "https://github.com/nicolai3008/pyneutron-bifrost"
Issues = "https://github.com/nicolai3008/pyneutron-bifrost/issues"