[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pygnuregex"
version = "1.1.5"
authors = [
  { name="Nikolaos Chatzikonstantinou", email="nchatz314@gmail.com" },
]
description = "An implementation of the GNU interface to regex in Python"
readme = "README.md"
license = "GPL-3.0-or-later"
license-files = ["COPYING"]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://codeberg.org/annoyingusername/pygnuregex/"
Issues = "https://codeberg.org/annoyingusername/pygnuregex/issues"

[project.optional-dependencies]
tests = [
    "pytest",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
