[project]
name = "pyfiglets"
version = "0.0.1"
authors = [
  { name="Gary Clark", email="gary@airoda.com" },
]
description = "Pure Python FIGlets Implementation"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Environment :: Console',
    'Intended Audience :: Developers',
    'Natural Language :: English',
    # For Katakana
    'Natural Language :: Japanese',
    # For Cyrillic
    'Natural Language :: Bulgarian',
    'Natural Language :: Bosnian',
    'Natural Language :: Macedonian',
    'Natural Language :: Russian',
    'Natural Language :: Serbian',
    'Operating System :: Unix',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Topic :: Text Processing',
    'Topic :: Text Processing :: Fonts',
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/airoda/pyfiglets"
Issues = "https://github.com/airoda/pyfiglets/issues"
