[project]
name = "agents-for-all"
version = "0.1.0"
description = "Modular agent framework combining LLMs and Tools"
requires-python = ">=3.10"
dependencies = [
    "openai>=1.77.0",
    "requests>=2.32.3",
]
readme = "README.md"
license = { text = "Apache-2.0" }
authors = [
    { name = "Sailesh Dhungana", email = "dhunganasailesh@gmail.com" }
]

[project.optional-dependencies]
dev = [
  "sphinx>=6.2.1",
  "furo>=2022.12.7",
  "graphviz>=0.20.1",
  "pytest>=7.4.0",
  "pytest-cov>=4.0.0",
  "pre-commit>=3.3.0",
  "build>=1.2.2.post1",
  "twine>=6.1.0",
]

[project.urls]
Homepage = "https://github.com/dhungana/agents-for-all.git"
Repository = "https://github.com/dhungana/agents-for-all"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
