[project]
name = "yuanqi-agent-test-mcp"
version = "0.1.0"
description = "mcp server to invoke yuanqi agent"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp>=1.7.1",
]
authors = [
    { name = "YuanqiMcp", email = "yuanqi_mcp@tencent.com" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
keywords = [
    "yuanqi",
    "agent",
    "mcp"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/yaunqi_agent_mcp"]

[tool.uv]
dev-dependencies = ["pyright>=1.1.389"]

[project.scripts]
yuanqi-agent-test-mcp = "yaunqi_agent_mcp:main"
