[tool.poetry]
name = "pydynamicestimator"
version = "0.4.7"
description = "A dynamic estimator for power systems"
authors = ["Milos Katanic <mkatanic@ethz.ch>"]
readme = "README.md"
exclude = ["coverage_reports/"]
license = "GPL-3.0-or-later"
repository = "https://gitlab.nccr-automation.ch/mkatanic/powerdynamicestimator"

[tool.poetry.dependencies]
python = "^3.10"
scipy = "^1.12.0"
matplotlib = "^3.8.3"
casadi = "^3.6.5"
pydantic = "^2.10.3"
sphinx = "^8.1.3"
tabulate = "^0.9.0"
nbsphinx = "^0.9.7"
numpy = "^2.2.4"
pandas = "^2.2.3"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
pytest-cov = "^5.0.0"
sphinx = "^8.1.3"
sphinx-rtd-theme = "^3.0.2"
sphinx-autodoc-typehints = "^3.0.1"
sphinxcontrib-napoleon = "^0.7"
ipykernel = "^6.29.5"
nbconvert = "^7.16.6"
nbclient = "^0.10.2"
flake8 = "^7.2.0"
pre-commit = "^4.2.0"
black = "^25.1.0"
sphinx-autoapi = "^3.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = "pydynamicestimator"
addopts = [
    "--import-mode=importlib",
]

[tool.poetry.scripts]
main = "pydynamicestimator.main:main"
pydynamicestimator = "pydynamicestimator.__main__:main"



