[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ademapkit"
version = "0.0.4"
description = "This is a package for all the countries in the world"
readme = "README.md"
authors = [{ name = "Abdullah Adesina Dhikrullah", email = "daadesina1@gmail.com" }]
license = { file = "LICENSE" }
dependencies = ["requests"]
requires-python = ">=3.10"

[tool.setuptools.package-data]
"ademapkit" = ["ademapkit.db"]
