[project]
name = "jwostik-pipeliner"
version = "1.0.1"
authors = [
  { name="Jwostik"},
]
description = "THE PIPELINER"
requires-python = ">=3.9"

[project.urls]
Homepage = "https://github.com/Jwostik/Pipeline"

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = []