[project]
name = "rpyc-ws"
version = "0.3.0"
description = "RPyC over WebSocket"
readme = "README.md"
authors = [{ name = "Luke Cummings", email = "luke.cummings@cenovus.com" }]
requires-python = ">=3.9"
dependencies = ["fastapi>=0.115.12", "rpyc>=6.0.2", "websockets>=15.0.1"]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["pyright>=1.1.400", "ruff>=0.11.8", "uvicorn[standard]>=0.34.2"]
