[build-system]
build-backend = "poetry.core.masonry.api"
requires = [ "poetry-core" ]

[tool.poetry]
name = "click-validators"
version = "v0.2.0"
description = "additional types for `click` parameter using `validators`."
authors = [ "Christoph DÃ¶rrer <d-chris@web.de>" ]
readme = "README.md"
packages = [ { include = "clicktypes" } ]
exclude = [ "clicktypes/__main__.py" ]
keywords = [ "click", "validators" ]
license = "MIT"
classifiers = [
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

[tool.poetry.urls]
repository = "https://github.com/d-chris/click-validators"
documentation = "https://d-chris.github.io/click-validators"

[tool.poetry.dependencies]
python = "^3.9"
click = ">=8.1.8"
validators = ">=0.34.0"
eth-hash = { version = ">=0.7.0", extras = [ "pycryptodome" ], optional = true }

[tool.poetry.extras]
crypto-eth-addresses = [ "eth-hash" ]
eth = [ "eth-hash" ]

[tool.poetry.group.dev.dependencies]
jinja2 = "^3.1.6"
black = ">=24.8.0"
tox = "^4.24.2"

[tool.poetry.group.docs.dependencies]
pdoc = ">=14.0.0"
pathlibutil = "^0.3.5"

[tool.poetry.group.test.dependencies]
pytest = "^8.3.5"
pytest-cov = ">=4.1.0"
pytest-randomly = "^3.15.0"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[[tool.poetry.source]]
name = "testpypi"
url = "https://test.pypi.org/legacy/"
priority = "explicit"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = "tests"
addopts = [
  "-s",
  "--color=yes",
  "--cov=clicktypes",
  "--cov-report=term-missing",
  "--cov-report=xml",
]

[tool.coverage.report]
exclude_lines = [ "@overload" ]

[tool.coverage.run]
omit = [ "*/__main__.py", "*/tests/*", "*/docs/*" ]
