[project]
authors = [{name = "Taka", email = "takahisa.amano@eodc.eu"}]
dependencies = [
  "dask<2026",
  "numpy<3",
  "xarray<2026",
  "zarr<4",
]
name = "extend-zarr"
requires-python = ">= 3.11,< 3.13"
dynamic = ["version"]
readme = "README.md"

[project.urls]
Homepage = "https://github.com/eodcgmbh/extend-zarr/"
Repository = "https://github.com/eodcgmbh/extend-zarr.git"
Issues =  "https://github.com/eodcgmbh/extend-zarr/issues"

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=64", "setuptools-scm>=8"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
extend_zarr = { path = ".", editable = true }

[tool.pixi.tasks]
check = "ruff check --fix --unsafe-fixes"
format = "ruff format"
style = { depends-on = ["check", "format"] }
test = "pytest -vvs"

[tool.setuptools_scm]
version_file = "src/extend_zarr/_version.py"

[tool.pixi.feature.development.dependencies]
isort = "*"
jupyterlab = "*"
jupyterlab-lsp = "*"
jupyterlab_code_formatter = "*"
jupyterlab_vim = "*"
ruff = "*"
setuptools-scm = "*"
twine = "*"

[tool.pixi.feature.test.dependencies]
pytest = "*"

[tool.pixi.feature.zarr2.dependencies]
zarr = ">=2.18.0,<3"

[tool.pixi.feature.zarr3.dependencies]
zarr = ">=3"

[tool.pixi.environments]
default = ["zarr2"]
development = ["zarr2", "test", "development"]
test-zarr2 = ["zarr2", "test"]
test-zarr3 = ["zarr3", "test"]


[tool.ruff]
line-length = 79

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
fixable = ["ALL"]
select = ["ALL"]
ignore = [
  "ANN003",
  "C901",
  "COM812",
  "D100",
  "D105",
  "D203",
  "D213",
  "ISC001",
  "PGH003",
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
  "D104",
]
"{tests,docs}/*" = [
  "ANN201",
  "D100",
  "D101",
  "D102",
  "D103",
  "INP001",
  "PLR0913",
  "PLR2004",
  "S101",
  ]

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"
multiline-quotes = "double"

[dependency-groups]
development = ["build"]
