[package]
#name = "werx_rust" # <-- Rust crate name
name = "werx" # <-- Rust crate name
version = "0.1.3"
edition = "2021"
resolver = "2" # <-- Avoid compiling unnecessary features from dependencies.

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "werx" # <-- This is the name of the compiled Python module
#name = "werx_rust"  # <-- Match the module-name in pyproject.toml
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.24.2", features = ["extension-module"] }
rayon = "1.10.0"

[profile.release]
lto = true          # <-- Enable Link-Time Optimization
codegen-units = 1   # <-- Single compilation unit for better optimization
opt-level = 3       # <-- Full optimization for speed
