[tool.poetry]
name = "proscenium"
version = "0.0.6"
description = "Frame AI Agents"
authors = ["Adam Pingel <oss@pingel.org>"]
license = "ASFv2"
readme = "README.md"
packages = [{include = "proscenium"}]

[tool.poetry.dependencies]
python = "^3.11"
aisuite = {extras = ["openai,anthropic"], version = "^0.1.10"}
rich = "^13.9.4"
typer = "^0.15.2"
python-dotenv = "^1.0.1"
pydantic = "^2.10.6"
stringcase = "^1.2.0"
docstring_parser = "^0.16"
pymilvus = {version = "^2.5.4"}
pymilvus_model = {version = "^0.3.1"}
datasets = "^3.3.2"
tiktoken = "^0.9.0"
neo4j = "^5.28.1"
gofannon = "^0.25.13"
langchain-community = "^0.3.18"
langchain-huggingface = "^0.1.2"
slack_sdk = "^3.35.0"

[tool.poetry.extras]
testing = ["pytest"]

[tool.poetry.scripts]
proscenium-bot = "proscenium.bin.bot:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
