[project]
name = "puzzle-apt-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    {name = "Puzzle", email = "data-puzzle@sk.com"}
]
license = {text = "MIT"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "build>=1.2.2.post1",
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
    "twine>=6.1.0",
]

[project.scripts]
puzzle-apt-mcp-server = "puzzlelabs.puzzle_apt_mcp_server.server:main"