[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "bencherscaffold"
version = "0.3.4"
description = ""
authors = [ "Leonard Papenmeier <leonard.papenmeier@posteo.de>",]
readme = "README.md"
license = "MIT"
[[tool.poetry.packages]]
include = "bencherscaffold"
from = "."

[tool.poetry.dependencies]
python = "^3.8"
grpcio = "^1.60.1"
protobuf = "^4.25.2"

[tool.poetry.group.dev.dependencies]
toml = "^0.10.2"
grpcio-tools = "1.62.2"
