[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "data-primer"
version = "0.0.3"
authors = [
  { name="Wang.Y", email="294961525@qq.com" },
]
description = "像'底漆'一样为数据做准备"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/WY-74/DataPrimer"
Issues = "https://github.com/WY-74/DataPrimer/issues"