[project]
name = "marcktools"
version = "0.3.0"
description = "A simple demo with MCP stdio support"
authors = [
    { name = "marckwei", email = "xiangwei1895@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp>=1.6.0",
]

[project.scripts]
marcktools = "marcktools.server:main"

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"