[build-system]
requires = ["maturin>=1.5,<2.0"]
build-backend = "maturin"

[project]
name = "propoptics"
description = "Generate noise signal based on PSD measurement and analyze the output"
authors = [{ name = "BenoÃ®t Sierro", email = "benoit.sierro@bluewin.ch" }]
readme = "README.md"
license = { file = "LICENSE" }

requires-python = ">=3.11"
dynamic = ["version"]
dependencies = [
    "matplotlib>=3.10.1",
    "numpy>=1.26.0",
    "scipy>=1.12.0",
    "click<8.2.0",
    "typer>=0.15.3",
]

keywords = [
    "noise",
    "dsp",
    "spectrum",
    "optical",
    "optics",
    "nonlinear",
    "laser",
    "pulse",
]
classifiers = [
    "License :: OSI Approved :: MIT License",

    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Topic :: Education",
    "Topic :: Scientific/Engineering :: Physics",

    "Programming Language :: Rust",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Typing :: Typed",
    "Operating System :: OS Independent",
]

[project.scripts]
propoptics = "propoptics.__main__:app"


[dependency-groups]
dev = ["ipython>=9.2.0", "maturin>=1.8.3,<2.0", "pytest>=8.3.5"]


[tool.maturin]
python-source = "python"
module-name = "propoptics._lib_propoptics"
features = ["pyo3/extension-module"]
compatibility = "manylinux_2_34"

[tool.ruff]
line-length = 100

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 92
