[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "darshika_khandelwal"
version = "0.3.0"
requires-python = ">=3.9"
description = "My first package!"
readme = "README.md"
authors = [
    {name = "Justin Furuness", email = "jfuruness@gmail.com"},
]
maintainers = [
  {name = "Justin Furuness", email = "jfuruness@gmail.com"}
]
license = {file = "LICENSE.txt"}
keywords = [
    "Furuness"
]
classifiers = [
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: Implementation :: CPython",
    "License :: OSI Approved :: BSD License",
    "Intended Audience :: Developers",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
    "Operating System :: MacOS :: MacOS X",
]
dependencies = [
    "colorama~=0.0"
]

[project.optional-dependencies]
dev = [
    "twine",
    "build"
]

[project.urls]
Homepage = "https://github.com/jfuruness/darshika_khandelwal"
Documentation = "https://github.com/jfuruness/darshika_khandelwal/README.md"

[project.scripts]
darshika_khandelwal = "darshika_khandelwal.__main__:main"