[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "evallm"
version = "0.1.1"
description = "A flexible task evaluation client"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }

authors = [
    { name = "Emre Kilic", email = "emre.kilic@std.bogazici.edu.tr" },
    { name = "Kristina Trajkovski", email = "kristina.trajkovski@std.bogazici.edu.tr" },
    { name = "Bilge Kaan Guneyli", email = "bilge.guneyli@std.bogazici.edu.tr" },
]

dependencies = [
    "typer>=0.15.3",
    "ollama>=0.4.8",
    "openai>=1.78.0",
    "beartype>=0.19.0",
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]

[project.optional-dependencies]
test = ["pytest"]

[project.urls]
Homepage = "https://github.com/tenacke/llm-evaluator"

[project.scripts]
evaluate = "evaluator.cli.main:main"
