[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "atla-insights"
version = "0.0.1a4"
description = "Atla is a platform for monitoring and improving AI agents."
readme = "README.md"
requires-python = ">=3.11"
license = { text = "MIT" }
authors = [{ name = "Atla Team", email = "support@atla-ai.com" }]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "logfire>=3.14.1",
    "openai>=1.77.0",
    "opentelemetry-api>=1.32.1",
    "opentelemetry-exporter-otlp-proto-grpc>=1.32.1",
    "pydantic>=2.11.4",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "pytest-asyncio>=0.26.0",
    "pytest-httpserver>=1.1.3",
    "litellm>=1.67.0",
    "litellm[proxy]",
]

[project.optional-dependencies]
ci = [
    "mypy>=1.15.0",
    "ruff>=0.11.7",
]
litellm = [
    "litellm>=1.67.0",
    "litellm[proxy]",
]

[project.urls]
"Homepage" = "https://atla-ai.com"
