[project]
name = "project-demo-juhi"
version = "0.1.2.3"
description = ""
authors = [
    {name = "Juhi",email = "juchic2811@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas (>=2.2.3,<3.0.0)",
    "scikit-learn (>=1.6.1,<2.0.0)",
    "xgboost (>=3.0.0,<4.0.0)",
    "pytest (>=8.3.5,<9.0.0)",
    "pyarrow (>=20.0.0,<21.0.0)",
]

[tool.poetry]
packages = [{include = "project_demo", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
