[project]
name = "TaskMcpClient"
version = "0.1.17"
description = "Localization configurable MCP client, interacting through task files"
readme = "README.md"
authors = [
    {name = "weiyf1225", email = "weiyf1225@qq.com"}
]
requires-python = ">=3.10"
dependencies = [
    "loguru>=0.7.3",
    "mcp>=1.6.0",
    "openai>=1.76.0",
    "python-dotenv>=1.1.0",
    "weberfuncs>=0.0.170",
]

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project.scripts]
TaskMcpClient = "TaskMcpClient:main"
